name: vbinds
pypi_name: blizzard-api
version: {{major}}.{{minor}}.{{patch}}
description: "Interact with Blizard's game-data API."
no_chdir_arg: true
setup_args:
- url_override="https://github.com/vkottler/keybinds/tree/master/wow"
- console_overrides=["bapi=vbinds.entry:main"]
