name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# add Python 3.9 back when it's fully supported by pylint etc.
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - uses: textbook/git-checkout-submodule-action@master
    - name: python${{matrix.python-version}} setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: secrethub/actions/env-export@v0.2.1
      env:
        SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
        BLIZZ_API_ID: secrethub://vdoer/keybinds/blizzard/id
        BLIZZ_API_SECRET: secrethub://vdoer/keybinds/blizzard/secret
    - name: install-mk
      run: |
        pip${{matrix.python-version}} install --upgrade vmklib
    - name: venv
      run: |
        mk -C wow -P vbinds PYTHON_VERSION=${{matrix.python-version}} venv
    - name: lint
      run: |
        mk -C wow -P vbinds PYTHON_VERSION=${{matrix.python-version}} lint
    - name: sa-types
      run: |
        mk -C wow -P vbinds PYTHON_VERSION=${{matrix.python-version}} python-sa-types
    - name: sa
      run: |
        mk -C wow -P vbinds PYTHON_VERSION=${{matrix.python-version}} sa
    - name: dist
      run: |
        mk -C wow -P vbinds PYTHON_VERSION=${{matrix.python-version}} dist
    - name: test
      run: |
        mk -C wow -P vbinds PYTHON_VERSION=${{matrix.python-version}} test PYTEST_EXTRA_ARGS="--cov-report=xml"
    - name: test-upload
      uses: codecov/codecov-action@v1
      with:
        files: ./wow/coverage.xml
        fail_ci_if_error: true
